print('Enter the first number:')
a = int(input())
print("Enter the second number:")
b = int(input())

print ("The addition of a and b equals to:", a+b)
print ("The subtraction of a and b equals to:", a-b)
print ("The division of a and b equals to:", a/b)
print ("The multiplication of a and b equals to:", a*b)
print ("The remainder of a and b is:", a%b)
print ("this is causing something")